---
ID: "fee1ed76-93c2-45b1-a071-fe24bfa4ec0c"
Parent: "13224246-40dd-4563-8386-f2f04426f760"
Template: "13224246-40dd-4563-8386-f2f04426f760"
Path: /sitecore/templates/LayoutSimulator/Page Types/Simulation Builder Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{03547A29-7056-4278-94A3-3EB5BE765660}">
        <r
          id="{99E74F5B-BC8E-439C-8E74-A67D554EFDD3}"
          ph="main"
          uid="{28DBA80D-DCD0-4EAE-935F-E917960F56C2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160328T232737Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
